version: '3'
services:
  stat:
    build: ./
    image: stat
    container_name: stat_ins
    restart: always
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./settings:/root/.jupyter
      - ./workspace:/workspace

